apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: partition-20-80
spec:
  action: partition
  mode: all
  selector:
    expressionSelectors:
      - key: bucket
        operator: In
        values: ["1", "2"]
  direction: to
  target:
    mode: all
    selector:
      expressionSelectors:
        - key: bucket
          operator: In
          values: ["0", "3", "4", "5", "6", "7", "8", "9"]